modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://github.com/KBheid/VanillaCrossover_PixelmonAddon"
#updateJSONURL="https://change.me.example.invalid/updates.json"
logoFile= "pixelblend.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

# Forge dependency
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft dependency
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "SERVER"

# Pixelmon dependency
[[dependencies."${mod_id}"]]
modId = "pixelmon"
mandatory = true
versionRange = "${pixelmon_version_range}"
ordering = "AFTER"
side = "BOTH"